cliente-transporte/src/main/java/com/transporte/domain/ConductorVehiculo.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.transporte.domain;

/**
 *
 * @author Usuario
 */
public class ConductorVehiculo {
    private Integer idConductorVehiculo;
    private Integer idConductor;
    private Integer idVehiculo;

    public ConductorVehiculo(Integer idConductorVehiculo) {
        this.idConductorVehiculo = idConductorVehiculo;
    }

    public ConductorVehiculo(Integer idConductor, Integer idVehiculo) {
        this.idConductor = idConductor;
        this.idVehiculo = idVehiculo;
    }

    public ConductorVehiculo() {
    }

    public Integer getIdConductorVehiculo() {
        return idConductorVehiculo;
    }

    public void setIdConductorVehiculo(Integer idConductorVehiculo) {
        this.idConductorVehiculo = idConductorVehiculo;
    }

    public Integer getIdConductor() {
        return idConductor;
    }

    public void setIdConductor(Integer idConductor) {
        this.idConductor = idConductor;
    }

    public Integer getIdVehiculo() {
        return idVehiculo;
    }

    public void setIdVehiculo(Integer idVehiculo) {
        this.idVehiculo = idVehiculo;
    }

    @Override
    public String toString() {
        return "ConductorVehiculo{" + "idConductorVehiculo=" + idConductorVehiculo + ", idConductor=" + idConductor + ", idVehiculo=" + idVehiculo + '}';
    }
    
    
    
}

cliente-transporte/src/main/java/com/transporte/web/ConductorBean.java
package com.transporte.web;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;
import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.Entity;
import javax.ws.rs.client.Invocation;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.GenericType;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import com.transporte.domain.Conductor;
import org.glassfish.jersey.client.ClientConfig;
import org.primefaces.event.RowEditEvent;

@Named("conductorBean")
@RequestScoped
public class ConductorBean {
    
    ClientConfig clientConfig = new ClientConfig();
    Client cliente = ClientBuilder.newClient(clientConfig);
    private static Invocation.Builder invocationBuilder;
    private static Response response;
    private static WebTarget webTarget;
    
    private Conductor conductorSeleccionado;
    
    List<Conductor> conductores;
    
    public ConductorBean(){
    }
    
    @PostConstruct
    public void inicializar(){
        //inicializar variables
        conductores = new ArrayList<>();
        WebTarget webTarget = cliente.target("http://localhost:8080/empresa-transporte/webservice").path("/conductores");
        conductores = webTarget.request(MediaType.APPLICATION_XML).get(Response.class).readEntity(new GenericType<List<Conductor>>(){});
        conductorSeleccionado = new Conductor();
    }
    
    public void editListener(RowEditEvent event){
        Conductor conductor = (Conductor) event.getObject();
        String path= "/" + conductor.getIdConductor();
        WebTarget webTarget = cliente.target("http://localhost:8080/empresa-transporte/webservice").path("/conductores");
        invocationBuilder = webTarget.path(path).request(MediaType.APPLICATION_XML);
        response = invocationBuilder.put(Entity.entity(conductor,MediaType.APPLICATION_XML));
    }

    public Conductor getConductorSeleccionado() {
        return conductorSeleccionado;
    }

    public void setConductorSeleccionado(Conductor conductorSeleccionado) {
        this.conductorSeleccionado = conductorSeleccionado;
    }

    public List<Conductor> getConductors() {
        
        return conductores;
    }

    public void setConductors(List<Conductor> conductores) {
        this.conductores = conductores;
    }
    
    public void agregarConductor(){
        WebTarget webTarget = cliente.target("http://localhost:8080/empresa-transporte/webservice").path("/conductores");
        invocationBuilder = webTarget.request(MediaType.APPLICATION_XML);
        response=invocationBuilder.post(Entity.entity(conductorSeleccionado, MediaType.APPLICATION_XML));
        this.conductores.add(conductorSeleccionado);
        this.conductorSeleccionado = null;
    }
    
    public void eliminarConductor(Conductor conductor){
        WebTarget webTarget = cliente.target("http://localhost:8080/empresa-transporte/webservice").path("/conductores");
        String pathEliminar= "/" + conductor.getIdConductor();
        invocationBuilder = webTarget.path(pathEliminar).request(MediaType.APPLICATION_XML);
        response = invocationBuilder.delete();
        this.conductores.remove(conductor);
        this.conductorSeleccionado = null;
    }
    
    public void reiniciarConductorSeleccionado(){
        this.conductorSeleccionado = new Conductor();
    }
}

cliente-transporte/src/main/java/com/transporte/web/ConfiguracionBean.java
package com.transporte.web;

import javax.enterprise.context.ApplicationScoped;
import javax.faces.annotation.FacesConfig;
import static javax.faces.annotation.FacesConfig.Version.JSF_2_3;

@FacesConfig(
        version=JSF_2_3
)
@ApplicationScoped
public class ConfiguracionBean {
    
}

cliente-transporte/src/main/java/com/transporte/web/EmpresaBean.java
package com.transporte.web;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.ws.rs.client.Entity;
import javax.inject.Named;
import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.Invocation;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.GenericType;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import com.transporte.domain.Empresa;
import org.glassfish.jersey.client.ClientConfig;
import org.primefaces.event.RowEditEvent;

@Named("empresaBean")
@RequestScoped
public class EmpresaBean {
    
    ClientConfig clientConfig = new ClientConfig();
    Client cliente = ClientBuilder.newClient(clientConfig);
    private static Invocation.Builder invocationBuilder;
    private static Response response;
    private static WebTarget webTarget;
    public static String ROL = "";
    
    private Empresa empresaSeleccionada;
    
    List<Empresa> empresas;
    
    public EmpresaBean(){
    }
    
    @PostConstruct
    public void inicializar(){
        //inicializar variables
        empresas = new ArrayList<>();
        WebTarget webTarget = cliente.target("http://localhost:8080/empresa-transporte/webservice").path("/empresas");
        empresas = webTarget.request(MediaType.APPLICATION_XML).get(Response.class).readEntity(new GenericType<List<Empresa>>(){});
        empresaSeleccionada = new Empresa();
    }
    
    public String navegar(String rol){
        ROL = rol;
        if(rol.equals("ADMIN"))
            return "listarEmpresas";
        return "seleccionarOpcionUsuario";
    }
    
    public String navegarSiguiente(String rol){
        ROL = rol;
        return "listarEmpresas";
    }
    
    public String obtenerRol(){
        return ROL;
    }
    
    public void editListener(RowEditEvent event){
        Empresa empresa = (Empresa) event.getObject();
        String path= "/" + empresa.getIdEmpresa();
        WebTarget webTarget = cliente.target("http://localhost:8080/empresa-transporte/webservice").path("/empresas");
        invocationBuilder = webTarget.path(path).request(MediaType.APPLICATION_XML);
        response = invocationBuilder.put(Entity.entity(empresa,MediaType.APPLICATION_XML));
    }

    public Empresa getEmpresaSeleccionada() {
        return empresaSeleccionada;
    }

    public void setEmpresaSeleccionada(Empresa empresaSeleccionada) {
        this.empresaSeleccionada = empresaSeleccionada;
    }

    public List<Empresa> getEmpresas() {
        
        return empresas;
    }

    public void setEmpresas(List<Empresa> empresas) {
        this.empresas = empresas;
    }
    
    public void agregarEmpresa(){
        WebTarget webTarget = cliente.target("http://localhost:8080/empresa-transporte/webservice").path("/empresas");
        invocationBuilder = webTarget.request(MediaType.APPLICATION_XML);
        response=invocationBuilder.post(Entity.entity(empresaSeleccionada, MediaType.APPLICATION_XML));
        //this.empresaService.registrarEmpresa(empresaSeleccionada);
        this.empresas.add(empresaSeleccionada);
        this.empresaSeleccionada = null;
    }
    
    public void eliminarEmpresa(Empresa empresa){
        WebTarget webTarget = cliente.target("http://localhost:8080/empresa-transporte/webservice").path("/empresas");
        String pathEliminar= "/" + empresa.getIdEmpresa();
        invocationBuilder = webTarget.path(pathEliminar).request(MediaType.APPLICATION_XML);
        response = invocationBuilder.delete();
        this.empresas.remove(empresa);
        this.empresaSeleccionada = null;
    }
    
    public void reiniciarEmpresaSeleccionada(Empresa empresa){
        this.empresaSeleccionada = new Empresa();
    }

    public String getROL() {
        return ROL;
    }

    public void setROL(String ROL) {
        this.ROL = ROL;
    }

    
    
    
    
}

cliente-transporte/src/main/java/com/transporte/web/VehiculoBean.java
package com.transporte.web;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;
import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.Entity;
import javax.ws.rs.client.Invocation;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.GenericType;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import com.transporte.domain.Conductor;
import com.transporte.domain.ConductorVehiculo;
import com.transporte.domain.Empresa;
import com.transporte.domain.Vehiculo;
import org.glassfish.jersey.client.ClientConfig;
import org.primefaces.event.RowEditEvent;

@Named("vehiculoBean")
@RequestScoped
public class VehiculoBean {

    ClientConfig clientConfig = new ClientConfig();
    Client cliente = ClientBuilder.newClient(clientConfig);
    private static Invocation.Builder invocationBuilder;
    private static Response response;
    private static WebTarget webTarget;

    private Vehiculo vehiculoSeleccionado;
    public static int idEmpresaSeleccionada;
    private static int idConductorSeleccionado;

    List<Vehiculo> vehiculos;
    List<ConductorVehiculo> conductoresVehiculos;
    private static List<Integer> idsVehiculosConductor;

    public VehiculoBean() {
    }

    @PostConstruct
    public void inicializar() {
            vehiculos = new ArrayList<>();
            WebTarget webTarget = cliente.target("http://localhost:8080/empresa-transporte/webservice").path("/vehiculos");
            vehiculos = webTarget.request(MediaType.APPLICATION_XML).get(Response.class).readEntity(new GenericType<List<Vehiculo>>() {
            });
            vehiculoSeleccionado = new Vehiculo();
    }

    public void editListener(RowEditEvent event) {
        Vehiculo vehiculo = (Vehiculo) event.getObject();
        String path = "/" + vehiculo.getIdVehiculo();
        WebTarget webTarget = cliente.target("http://localhost:8080/empresa-transporte/webservice").path("/vehiculos");
        invocationBuilder = webTarget.path(path).request(MediaType.APPLICATION_XML);
        response = invocationBuilder.put(Entity.entity(vehiculo, MediaType.APPLICATION_XML));
    }

    public Vehiculo getVehiculoSeleccionado() {
        return vehiculoSeleccionado;
    }

    public void setVehiculoSeleccionado(Vehiculo vehiculoSeleccionado) {
        this.vehiculoSeleccionado = vehiculoSeleccionado;
    }

    public List<Vehiculo> getVehiculos() {
        return vehiculos;
    }

    public void setVehiculos(List<Vehiculo> vehiculos) {
        this.vehiculos = vehiculos;
    }

    public void agregarVehiculo() {
        WebTarget webTarget = cliente.target("http://localhost:8080/empresa-transporte/webservice").path("/vehiculos");
        invocationBuilder = webTarget.request(MediaType.APPLICATION_XML);
        response = invocationBuilder.post(Entity.entity(vehiculoSeleccionado, MediaType.APPLICATION_XML));
        this.vehiculos.add(vehiculoSeleccionado);
        this.vehiculoSeleccionado = null;
    }

    public void eliminarVehiculo(Vehiculo vehiculo) {
        WebTarget webTarget = cliente.target("http://localhost:8080/empresa-transporte/webservice").path("/vehiculos");
        String pathEliminar = "/" + vehiculo.getIdVehiculo();
        invocationBuilder = webTarget.path(pathEliminar).request(MediaType.APPLICATION_XML);
        response = invocationBuilder.delete();
        this.vehiculos.remove(vehiculo);
        this.vehiculoSeleccionado = null;
    }

    public void reiniciarVehiculoSeleccionada() {
        this.vehiculoSeleccionado = new Vehiculo();
    }

    public void reiniciarEmpresaSeleccionada(Empresa empresa) {
        idEmpresaSeleccionada = empresa.getIdEmpresa();

        Iterator< Vehiculo> it = vehiculos.iterator();
        while (it.hasNext()) {
            Vehiculo vh = it.next();
            if ((vh.getIdEmpresa() != null && vh.getIdEmpresa() == idEmpresaSeleccionada) || vh.getIdEmpresa() == null) {
                if (vh.getIdEmpresa() != null && vh.getIdEmpresa() == idEmpresaSeleccionada) {
                    vh.setMarcado(true);
                } else {
                    vh.setMarcado(false);
                }
            } else {
                vh.setMarcado(true);
            }
        }
        

    }

    public void reiniciarConductorSeleccionado(Conductor conductor) {
        idConductorSeleccionado = conductor.getIdConductor();

        List<Integer> vehiculosPorIdConductor = new ArrayList<>();
        idsVehiculosConductor = new ArrayList<>();
        conductoresVehiculos = new ArrayList<>();
        WebTarget webTarget = cliente.target("http://localhost:8080/empresa-transporte/webservice").path("/conductores_vehiculos");
        conductoresVehiculos = webTarget.request(MediaType.APPLICATION_JSON).get(Response.class).readEntity(new GenericType<List<ConductorVehiculo>>() {
        });
        for (ConductorVehiculo conVeh : conductoresVehiculos) {
            if (conVeh.getIdConductor() == idConductorSeleccionado) {
                vehiculosPorIdConductor.add(conVeh.getIdVehiculo());
                idsVehiculosConductor.add(conVeh.getIdConductorVehiculo());
            }
        }

        Iterator< Vehiculo> it = vehiculos.iterator();
        while (it.hasNext()) {
            Vehiculo vh = it.next();

            if (vehiculosPorIdConductor.contains(vh.getIdVehiculo())) {
                vh.setMarcado(true);
            } else {
                vh.setMarcado(false);
            }

        }

    }

    public void actualizarVehiculosEmpresa() {
        for (Vehiculo v : vehiculos) {
            if (v.isMarcado()) {
                v.setIdEmpresa(idEmpresaSeleccionada);
            } else {
                if (v.getIdEmpresa() != null && v.getIdEmpresa() == idEmpresaSeleccionada) {
                    v.setIdEmpresa(null);
                }
            }
            String path = "/" + v.getIdVehiculo();
            WebTarget webTarget = cliente.target("http://localhost:8080/empresa-transporte/webservice").path("/vehiculos");
            invocationBuilder = webTarget.path(path).request(MediaType.APPLICATION_XML);
            response = invocationBuilder.put(Entity.entity(v, MediaType.APPLICATION_XML));
        }
        idEmpresaSeleccionada = 0;

    }

    public void actualizarVehiculosConductores() {
        List<Integer> idVehiculos = new ArrayList<>();
        WebTarget webTarget = cliente.target("http://localhost:8080/empresa-transporte/webservice").path("/conductores_vehiculos");
        for (Integer i : idsVehiculosConductor) {
            
            String pathEliminar = "/" + i;
            invocationBuilder = webTarget.path(pathEliminar).request(MediaType.APPLICATION_XML);
            response = invocationBuilder.delete();
        }
        idsVehiculosConductor = null;

        for (Vehiculo vh : vehiculos) {
            if (vh.isMarcado()) {
                invocationBuilder = webTarget.request(MediaType.APPLICATION_XML);
                response = invocationBuilder.post(Entity.entity(new ConductorVehiculo(idConductorSeleccionado, vh.getIdVehiculo()), MediaType.APPLICATION_JSON));
            }
        }

        idConductorSeleccionado = 0;

    }

    public static int getIdEmpresaSeleccionada() {
        return idEmpresaSeleccionada;
    }

    public boolean validarEmpresaVehiculo(Integer id){
        return id != null && id != idEmpresaSeleccionada ? true : false;
    }
}

cliente-transporte/src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Sistema SGA</title>
    </h:head>
    <h:body>
        <h2>Sistema SGA</h2>
        <h:form>
            
            <p:commandButton value="Administrador" action="#{empresaBean.navegar('ADMIN')}" ajax="false" />
            <br/><br/>
            <p:commandButton value="Usuario Empresa" action="#{empresaBean.navegar('USER')}" ajax="false" />
        </h:form>
    </h:body>
</html>

cliente-transporte/src/main/webapp/listarConductores.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Listado de vehículos</title>
    </h:head>
    <h:body>

        <h:form id="conductorsListForm">
            <p:growl id="messages" showDetail="true"/>
            <p:messages />
            <p:dataTable id="conductorsDataTable" value="#{conductorBean.conductors}" var="conductor" editable="true" rowKey="#{conductor.idConductor}"
                         selection="#{conductorBean.conductorSeleccionado}" >
                <f:facet name="header">
                    Listado de Conductores
                </f:facet>

                <p:column headerText="Tipo Identificación">
                    <p:cellEditor>
                        <f:facet name="output">
                            <h:outputText value="#{conductor.tipoIdentificacion}" />
                        </f:facet>
                        <f:facet name="input">
                            <p:inputText value="#{conductor.tipoIdentificacion}" />
                        </f:facet>
                    </p:cellEditor>
                </p:column>

                <p:column headerText="Número Identificación">
                    <p:cellEditor>
                        <f:facet name="output">
                            <h:outputText value="#{conductor.numeroIdentificacion}" />
                        </f:facet>
                        <f:facet name="input">
                            <p:inputText value="#{conductor.numeroIdentificacion}" />
                        </f:facet>
                    </p:cellEditor>
                </p:column>

                <p:column headerText="Nombre Completo">
                    <p:cellEditor>
                        <f:facet name="output">
                            <h:outputText value="#{conductor.nombreCompleto}" />
                        </f:facet>
                        <f:facet name="input">
                            <p:inputText value="#{conductor.nombreCompleto}" />
                        </f:facet>
                    </p:cellEditor>
                </p:column>

                <p:column headerText="Dirección">
                    <p:cellEditor>
                        <f:facet name="output">
                            <h:outputText value="#{conductor.direccion}" />
                        </f:facet>
                        <f:facet name="input">
                            <p:inputText value="#{conductor.direccion}" />
                        </f:facet>
                    </p:cellEditor>
                </p:column>

                <p:column headerText="Ciudad">
                    <p:cellEditor>
                        <f:facet name="output">
                            <h:outputText value="#{conductor.ciudad}" />
                        </f:facet>
                        <f:facet name="input">
                            <p:inputText value="#{conductor.ciudad}" />
                        </f:facet>
                    </p:cellEditor>
                </p:column>

                <p:column headerText="Departamento">
                    <p:cellEditor>
                        <f:facet name="output">
                            <h:outputText value="#{conductor.departamento}" />
                        </f:facet>
                        <f:facet name="input">
                            <p:inputText value="#{conductor.departamento}" />
                        </f:facet>
                    </p:cellEditor>
                </p:column>

                <p:column headerText="Pais">
                    <p:cellEditor>
                        <f:facet name="output">
                            <h:outputText value="#{conductor.pais}" />
                        </f:facet>
                        <f:facet name="input">
                            <p:inputText value="#{conductor.pais}" />
                        </f:facet>
                    </p:cellEditor>
                </p:column>

                <p:column headerText="Telefono">
                    <p:cellEditor>
                        <f:facet name="output">
                            <h:outputText value="#{conductor.telefono}" />
                        </f:facet>
                        <f:facet name="input">
                            <p:inputText value="#{conductor.telefono}" />
                        </f:facet>
                    </p:cellEditor>
                </p:column>


                <f:facet name="footer">
                    <p:commandButton value="Regresar" action="seleccionarOpcionUsuario" />
                    <p:spacer height="5px" /> 
                    <p:commandButton value="Agregar" actionListener="#{conductorBean.reiniciarConductorSeleccionado}" update=":dialogForm" oncomplete="PF('conductorDialog').show()"/>
                </f:facet>

                <p:column headerText="Editar" style="width: 50px;">
                    <p:rowEditor />
                </p:column>

                <p:column headerText="Vehículos" style="width: 150px;">
                    <p:commandButton value="Modificar" actionListener="#{vehiculoBean.reiniciarConductorSeleccionado(conductor)}"  update="dialog2Form" oncomplete="PF('VehiculosDialog').show()"/>
                </p:column>

                <p:ajax event="rowEdit" listener="#{conductorBean.editListener}" />
            </p:dataTable>

            <p:contextMenu for="conductorsDataTable">
                <p:menuitem value="Eliminar" update="conductorsListForm:conductorsDataTable" icon="ui-icon-close" actionListener="#{conductorBean.eliminarConductor(conductor)}"/>
            </p:contextMenu>
        </h:form>

        <p:dialog id="conductorDig" widgetVar="conductorDialog" header="Agregar Conductor" modal="true" showEffect="fade" hideEffect="fade" resizable="false">
            <h:form id="dialogForm">
                <p:outputPanel id="conductorDetail" style="text-align: center">
                    <p:panelGrid id="display" columns="4" columnClasses="label, value" >
                        <h:outputText value="Tipo Identificación" />
                        <h:inputText value="#{conductorBean.conductorSeleccionado.tipoIdentificacion}" />

                        <h:outputText value="Número Identificación" />
                        <h:inputText value="#{conductorBean.conductorSeleccionado.numeroIdentificacion}" />

                        <h:outputText value="Nombre Completo" />
                        <h:inputText value="#{conductorBean.conductorSeleccionado.nombreCompleto}" />

                        <h:outputText value="Dirección" />
                        <h:inputText value="#{conductorBean.conductorSeleccionado.direccion}" />

                        <h:outputText value="Ciudad" />
                        <h:inputText value="#{conductorBean.conductorSeleccionado.ciudad}" />

                        <h:outputText value="Departamento" />
                        <h:inputText value="#{conductorBean.conductorSeleccionado.departamento}" />

                        <h:outputText value="País" />
                        <h:inputText value="#{conductorBean.conductorSeleccionado.pais}" />

                        <h:outputText value="Teléfono" />
                        <h:inputText value="#{conductorBean.conductorSeleccionado.telefono}" />

                        <f:facet name="footer">
                            <p:commandButton value="Agregar" actionListener="#{conductorBean.agregarConductor}" update="display,:conductorsListForm:conductorsDataTable" oncomplete="PF('conductorDialog').hide();"/>
                        </f:facet>
                    </p:panelGrid>
                </p:outputPanel>
            </h:form>
        </p:dialog>
        
        <p:dialog id="vehiculoDig" widgetVar="VehiculosDialog" header="Marcar/Desmarcar Vehículos" modal="true" showEffect="fade" hideEffect="fade" resizable="false">
            <h:form id="dialog2Form">
                <p:outputPanel id="vehiculoDetail" style="text-align: center">
                    <p:panelGrid id="display" columns="4" columnClasses="label, value" >
                        <p:dataTable id="vehiculosDataTable" value="#{vehiculoBean.vehiculos}" var="vehiculo" editable="true" rowKey="#{vehiculo.idVehiculo}"
                                     >
                            <f:facet name="header">
                                Listado de Vehiculos
                            </f:facet>
                            
                            <p:column >
                                <p:selectBooleanCheckbox value="#{vehiculo.marcado}" />
                            </p:column>

                            <p:column headerText="Placa">
                                <h:outputText value="#{vehiculo.placa}" />
                            </p:column>

                            <p:column headerText="Modelo">
                                <h:outputText value="#{vehiculo.modelo}" />
                            </p:column>

                            <p:column headerText="Marca">
                                <h:outputText value="#{vehiculo.marca}" />
                            </p:column>
                        </p:dataTable>
                        <f:facet name="footer">
                            <p:commandButton value="Agregar" actionListener="#{vehiculoBean.actualizarVehiculosConductores}" update="display,:conductorsListForm:conductorsDataTable" oncomplete="PF('VehiculosDialog').hide();"/>
                        </f:facet>
                    </p:panelGrid>
                </p:outputPanel>
            </h:form>
        </p:dialog>

    </h:body>
</html>

cliente-transporte/src/main/webapp/seleccionarOpcionUsuario.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Sistema Transportes</title>
    </h:head>
    <h:body>
        <h2>Sistema SGA</h2>
        <h:form>
            <p:commandButton value="Empresas" action="#{empresaBean.navegarSiguiente('USER')}" ajax="false" />
            <br/><br/>
            <p:commandButton value="Vehículos" action="listarVehiculos" ajax="false" />
            <br/><br/>
            <p:commandButton value="Conductores" action="listarConductores" ajax="false" />
        </h:form>
    </h:body>
</html>